# Generated by Django 4.2 on 2025-10-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(help_text='Separate each responsibility with a comma')),
                ('tech_stack', models.CharField(help_text='Comma-separated tech stack', max_length=200)),
                ('icon_class', models.CharField(default='fas fa-laptop-code', max_length=100)),
                ('delay', models.FloatField(default=0)),
            ],
        ),
    ]
